name: Goodreads Scraper Healthcheck

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  test:
    name: Test Goodreads Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests (first attempt)
        id: first
        continue-on-error: true
        run: cargo test -- --test-threads=1

      - name: Retry tests if first attempt failed
        if: ${{ steps.first.outcome == 'failure' }}
        id: retry
        continue-on-error: true
        run: |
          echo "Retrying after 30s..."
          sleep 30
          cargo test -- --test-threads=1

      - name: Fail if both attempts failed
        if: ${{ steps.first.outcome == 'failure' && steps.retry.outcome == 'failure' }}
        run: |
          echo "Tests failed after retry"
          exit 1

      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v6
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          to: ${{ secrets.MAIL_TARGET }}
          from: Goodreads Metadata Scraper
          subject: "Goodreads Scraper Test Failed"
          body: |
            The Goodreads scraper tests failed after one retry.
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

